[build]
  base = "client/"
  publish = "client/build/"
  command = "npm ci --prefer-offline --no-audit --no-fund && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"

# Skip unnecessary processing
[build.processing]
  skip_processing = false

# Basic redirects only
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200